; =========================================================
; CẤU HÌNH CHUNG CHO CẢ 2 MẠCH (Kế thừa cho các env bên dưới)
; =========================================================
[env]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; =========================================================
; MÔI TRƯỜNG 1: DÀNH CHO WORKER (THIẾT BỊ ĐEO)
; =========================================================
[env:worker]
; Chỉ biên dịch file main.cpp, tự động bỏ qua file Anchor.cpp
build_src_filter = +<*> -<Anchor.cpp> 

lib_deps = 
    https://github.com/thotro/arduino-dw1000.git
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.4

; =========================================================
; MÔI TRƯỜNG 2: DÀNH CHO ANCHOR (TRẠM CỐ ĐỊNH)
; =========================================================
[env:anchor]
; Chỉ biên dịch file Anchor.cpp, tự động bỏ qua file main.cpp
build_src_filter = +<*> -<main.cpp>

lib_deps = 
    https://github.com/thotro/arduino-dw1000.git
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.4